"""
Step 3 - Export a training-ready YOLO-pose dataset.

Reads annotations.json (your corrected keypoints) and writes a clean dataset:

    dataset/
      images/train/*  images/val/*
      labels/train/*  labels/val/*
      data.yaml

data.yaml carries kpt_shape [12, 3], flip_idx (left<->right mirror), the single
"court" class, and the 12 keypoint names. Ready for:

    yolo pose train data=<...>/dataset/data.yaml model=yolo11n-pose.pt imgsz=1280

Usage:
    python export_yolo.py                 # all images that have a usable label
    python export_yolo.py --reviewed-only # only images you marked reviewed
    python export_yolo.py --val-split 0.15
    python export_yolo.py --copy          # copy images (default: symlink, fallback copy)
"""

import argparse
import os
import random
import shutil
import sys

import common as C


def get_args():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description="Export YOLO-pose dataset from annotations.json")
    ap.add_argument("--config", default=os.path.join(here, "config.json"))
    ap.add_argument("--images", default=None)
    ap.add_argument("--reviewed-only", action="store_true",
                    help="export only images marked reviewed in the editor")
    ap.add_argument("--val-split", type=float, default=None)
    ap.add_argument("--copy", action="store_true",
                    help="copy image files instead of symlinking")
    return ap.parse_args(), here


def place(src, dst, do_copy):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    if os.path.exists(dst):
        os.remove(dst)
    if not do_copy:
        try:
            os.symlink(os.path.abspath(src), dst)
            return
        except (OSError, NotImplementedError):
            pass  # symlink not permitted (common on Windows) -> copy
    shutil.copy2(src, dst)


def write_data_yaml(path, dataset_dir):
    flip = ", ".join(str(i) for i in C.FLIP_IDX)
    names = "\n".join(f"  {i}: {n}" for i, n in enumerate(C.KPT_NAMES))
    txt = f"""# YOLO-pose dataset for pickleball court keypoints
# Generated by pb_relabel_tool/export_yolo.py
path: {dataset_dir.replace(os.sep, '/')}
train: images/train
val: images/val

# single object class
nc: 1
names:
  0: court

# 12 keypoints, each (x, y, visibility)
kpt_shape: [{C.NUM_KPTS}, 3]
# left<->right mirror map for horizontal-flip augmentation
flip_idx: [{flip}]

# keypoint index -> meaning (reference; not used by the trainer)
kpt_names:
{names}
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(txt)


def main():
    args, here = get_args()
    cfg = C.load_config(args.config)
    base_dir = os.path.dirname(os.path.abspath(args.config)) if os.path.exists(args.config) else here
    images_dir, work_dir = C.resolve_dirs(cfg, base_dir)
    if args.images:
        images_dir = os.path.abspath(args.images)
    paths = C.work_paths(work_dir)
    val_split = args.val_split if args.val_split is not None else cfg.get("val_split", 0.2)
    pad = cfg.get("bbox_pad_frac", 0.02)

    ann = C.load_annotations(paths["annotations"])
    imgs = ann.get("images", {})
    if not imgs:
        sys.exit(f"[error] no annotations found at {paths['annotations']} - run run_inference.py first.")

    # collect exportable items (must yield a valid YOLO line)
    items = []
    skipped_unreviewed = skipped_nolabel = 0
    for fname, rec in sorted(imgs.items()):
        if args.reviewed_only and not rec.get("reviewed"):
            skipped_unreviewed += 1
            continue
        w, h = rec.get("width"), rec.get("height")
        kpts = rec.get("keypoints", [])
        line = C.keypoints_to_yolo_line(kpts, w, h, pad) if (w and h) else None
        if not line:
            skipped_nolabel += 1
            continue
        if not os.path.exists(os.path.join(images_dir, fname)):
            print(f"  [warn] image file missing, skipping: {fname}")
            continue
        items.append((fname, line))

    if not items:
        sys.exit("[error] nothing to export (no images with a usable label). "
                 "Use the editor to place/correct points first, "
                 "or drop --reviewed-only.")

    random.seed(cfg.get("seed", 42))
    random.shuffle(items)
    n_val = int(round(len(items) * val_split))
    val_set = set(f for f, _ in items[:n_val])

    dataset_dir = paths["dataset"]
    for sub in ("images/train", "images/val", "labels/train", "labels/val"):
        os.makedirs(os.path.join(dataset_dir, sub), exist_ok=True)

    n_train = n_v = 0
    for fname, line in items:
        split = "val" if fname in val_set else "train"
        place(os.path.join(images_dir, fname),
              os.path.join(dataset_dir, "images", split, fname),
              args.copy)
        with open(os.path.join(dataset_dir, "labels", split, C.label_name_for(fname)),
                  "w", encoding="utf-8") as f:
            f.write(line + "\n")
        if split == "val":
            n_v += 1
        else:
            n_train += 1

    write_data_yaml(os.path.join(dataset_dir, "data.yaml"), dataset_dir)

    print(f"Exported {len(items)} images -> {dataset_dir}")
    print(f"  train: {n_train}   val: {n_v}")
    if skipped_unreviewed:
        print(f"  skipped (not reviewed): {skipped_unreviewed}")
    if skipped_nolabel:
        print(f"  skipped (no usable label): {skipped_nolabel}")
    print(f"\ndata.yaml: {os.path.join(dataset_dir, 'data.yaml')}")
    print("Train with, e.g.:")
    print(f"  yolo pose train data=\"{os.path.join(dataset_dir, 'data.yaml')}\" "
          f"model=yolo11n-pose.pt epochs=100 imgsz=1280")


if __name__ == "__main__":
    main()
